CREATE TABLE IF NOT EXISTS devices (
    token       TEXT PRIMARY KEY,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE devices ADD COLUMN IF NOT EXISTS warnings BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE devices ADD COLUMN IF NOT EXISTS sound TEXT NOT NULL DEFAULT 'alert.caf';

ALTER TABLE devices ADD COLUMN IF NOT EXISTS la_start_token TEXT;

ALTER TABLE devices ADD COLUMN IF NOT EXISTS la_update_token TEXT;

ALTER TABLE devices ADD COLUMN IF NOT EXISTS critical BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE devices ADD COLUMN IF NOT EXISTS critical_volume DOUBLE PRECISION NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS pushes (
    id        BIGSERIAL PRIMARY KEY,
    channel   TEXT NOT NULL,
    type      TEXT NOT NULL,
    severity  TEXT NOT NULL,
    text      TEXT NOT NULL,
    pushed    BOOLEAN NOT NULL DEFAULT true,
    ts        TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE pushes ADD COLUMN IF NOT EXISTS pushed BOOLEAN NOT NULL DEFAULT true;

CREATE INDEX IF NOT EXISTS idx_pushes_ts ON pushes (ts DESC);

CREATE INDEX IF NOT EXISTS idx_pushes_ts_id ON pushes (ts DESC, id DESC);
